apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: recommendation-service
  name: recommendation-service
  namespace: recommendation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation-service
  template:
    metadata:
      labels:
        app: recommendation-service
    spec:
      containers:
      - image: __ACCOUNT_ID__.dkr.ecr.__AWS_REGION__.amazonaws.com/recommendation-service
        name: recommendation-service
        ports:
        - containerPort: 5000
        resources: # Verify the amount of requests
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: OTLP
          value: "otel-collector.otel-collector.svc.cluster.local"
        - name: DATABASE
          value: "database-service.database-service.svc.cluster.local"
        - name: LOGS
          value: "analytics-service.analytics-service.svc.cluster.local" # Analytics Service
        - name: INVENTORY
          value: "inventory-service.inventory-service.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: recommendation-service
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: recommendation-service