apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: authentication-service
  name: authentication-service
  namespace: authentication-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - image: __ACCOUNT_ID__.dkr.ecr.__AWS_REGION__.amazonaws.com/authentication-service
        name: authentication-service
        ports:
        - containerPort: 5000
        resources: # Verify the amount of requests
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: OTLP
          value: "otel-collector.otel-collector.svc.cluster.local"
        - name: RECOMMEND
          value: "recommendation-service.recommendation-service.svc.cluster.local"
        - name: LOGS
          value: "analytics-service.analytics-service.svc.cluster.local" # Analytics Service
        
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: authentication-service
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: authentication-service