version: "3.8"
services:
  fluent-bit:
    image: fluent/fluent-bit:latest
    ports:
      - '24224:24224' # logging port
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
  data-prepper:
    restart: unless-stopped
    container_name: data-prepper
    image: opensearchproject/data-prepper:latest
    command: sh data-prepper-wait-for-odfe-and-start.sh
    volumes:
      - ./data-prepper-wait-for-odfe-and-start.sh:/usr/share/data-prepper/data-prepper-wait-for-odfe-and-start.sh
      - ./trace_analytics_no_ssl.yml:/usr/share/data-prepper/pipelines.yaml
      - ./data-prepper-config.yaml:/usr/share/data-prepper/data-prepper-config.yaml
      - ./root-ca.pem:/usr/share/data-prepper/root-ca.pem
    ports:
      - "21890:21890"
    networks:
      - my_network
    logging:
      driver: fluentd
  otel-collector:
    restart: unless-stopped
    image: otel/opentelemetry-collector:0.46.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
      - ./demo-data-prepper.crt:/etc/demo-data-prepper.crt
    ports:
      - "55680:55680"
    depends_on:
      - data-prepper
    logging:
      driver: fluentd
    networks:
      - my_network
  mysql:
    restart: unless-stopped
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    logging:
      driver: fluentd
    networks:
      - my_network
  sample-app:
    restart: unless-stopped
    build:
      context: sample-app
      dockerfile: Dockerfile
    ports:
      - '8082:8082' # inventory
      - '8083:8083' # database
      - '8084:8084' # payment
      - '8085:8085' # auth
      - '8086:8086' # recommendation
      - '8087:8087' # analytics-service
      - '8088:8088' # order
      - '8089:8089' # client-dashboard
    environment:
      - OTEL_EXPORTER=otlp # protocolo
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:55680 # DNS
      - OTEL_RESOURCE_ATTRIBUTES=service.name=analytics-service # Service Name
      - OTLP=otel-collector # Using in Pyhton
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - WAIT_HOSTS=otel-collector:55680, mysql:3306
    depends_on:
      - otel-collector
      - mysql
    networks:
      - my_network
    logging:
      driver: fluentd
networks:
  my_network:
  
